export const INVOICES_GET_SUCCESS = "INVOICES_GET_SUCCESS";
export const INVOICES_GET_FAIL = "INVOICES_GET_FAIL";
export const INVOICES_LOADING_START = "INVOICES_LOADING_START";
export const INVOICES_LOADING_END = "INVOICES_LOADING_END";