export const SINGLE_ORDER_GET_SUCCESS = "SINGLE_ORDER_GET_SUCCESS";
export const SINGLE_ORDER_GET_FAIL = "SINGLE_ORDER_GET_FAIL";
export const SINGLE_ORDER_SAVE_SUCCESS = "SINGLE_ORDER_SAVE_SUCCESS";
export const SINGLE_ORDER_SAVE_FAIL = "SINGLE_ORDER_SAVE_FAIL";
export const SINGLE_ORDER_LOADING_START = "SINGLE_ORDER_LOADING_START";
export const SINGLE_ORDER_LOADING_FINISH = "SINGLE_ORDER_LOADING_FINISH";