export const SINGLE_DELIVERY_GET_SUCCESS = "SINGLE_DELIVERY_GET_SUCCESS";
export const SINGLE_DELIVERY_GET_FAIL = "SINGLE_DELIVERY_GET_FAIL";
export const SINGLE_DELIVERY_SAVE_SUCCESS = "SINGLE_DELIVERY_SAVE_SUCCESS";
export const SINGLE_DELIVERY_SAVE_FAIL = "SINGLE_DELIVERY_SAVE_FAIL";
export const SINGLE_DELIVERY_LOADING_START = "SINGLE_DELIVERY_LOADING_START";
export const SINGLE_DELIVERY_LOADING_FINISH = "SINGLE_DELIVERY_LOADING_FINISH";