export const CLIENTS_GET_SUCCESS = "CLIENTS_GET_SUCCESS";
export const CLIENTS_GET_FAIL = "CLIENTS_GET_FAIL";
export const CLIENTS_LOADING_START = "CLIENTS_LOADING_START";
export const CLIENTS_LOADING_END = "CLIENTS_LOADING_END";